package com.basiliscoderoko.appescritorio;

import javax.swing.JFrame;

public class Principal extends javax.swing.JFrame {
    
    private VentasForm ventas = null;
    private ComprasForm compras = null;
    private ListadosForm listados = null;
    private MaestrosForm maestros = null;
    
    public Principal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        MenuVentas = new javax.swing.JMenu();
        VentasMenuItem = new javax.swing.JMenuItem();
        MenuCompras = new javax.swing.JMenu();
        ComprasMenuItem = new javax.swing.JMenuItem();
        MenuListados = new javax.swing.JMenu();
        ListadosMenuItem = new javax.swing.JMenuItem();
        MenuMaestros = new javax.swing.JMenu();
        MaestrosMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuVentas.setMnemonic('f');
        MenuVentas.setText("Ventas");

        VentasMenuItem.setMnemonic('x');
        VentasMenuItem.setText("Ventas");
        VentasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasMenuItemActionPerformed(evt);
            }
        });
        MenuVentas.add(VentasMenuItem);

        menuBar.add(MenuVentas);

        MenuCompras.setMnemonic('e');
        MenuCompras.setText("Compras");

        ComprasMenuItem.setMnemonic('p');
        ComprasMenuItem.setText("Compras");
        ComprasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprasMenuItemActionPerformed(evt);
            }
        });
        MenuCompras.add(ComprasMenuItem);

        menuBar.add(MenuCompras);

        MenuListados.setMnemonic('h');
        MenuListados.setText("Listados");

        ListadosMenuItem.setMnemonic('c');
        ListadosMenuItem.setText("Listados");
        ListadosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadosMenuItemActionPerformed(evt);
            }
        });
        MenuListados.add(ListadosMenuItem);

        menuBar.add(MenuListados);

        MenuMaestros.setText("Maestros");

        MaestrosMenuItem.setText("Maestros");
        MaestrosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaestrosMenuItemActionPerformed(evt);
            }
        });
        MenuMaestros.add(MaestrosMenuItem);

        menuBar.add(MenuMaestros);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VentasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasMenuItemActionPerformed
        if (ventas == null || ventas.isClosed()) {
            ventas = new VentasForm();
            this.desktopPane.add(this.ventas);
        }
        ventas.setVisible(true);
        
    }//GEN-LAST:event_VentasMenuItemActionPerformed

    private void ComprasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprasMenuItemActionPerformed
        
        if (compras == null || compras.isClosed()) {
            compras = new ComprasForm();
            this.desktopPane.add(this.compras);
        }
        compras.setVisible(true);
        

    }//GEN-LAST:event_ComprasMenuItemActionPerformed

    private void ListadosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadosMenuItemActionPerformed
        if (listados == null || listados.isClosed()) {
            listados = new ListadosForm();
            this.desktopPane.add(this.listados);
        }
        listados.setVisible(true);
    }//GEN-LAST:event_ListadosMenuItemActionPerformed

    private void MaestrosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaestrosMenuItemActionPerformed
        if (maestros == null || maestros.isClosed()) {
            maestros = new MaestrosForm();
            this.desktopPane.add(this.maestros);
        }
        maestros.setVisible(true);
    }//GEN-LAST:event_MaestrosMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ComprasMenuItem;
    private javax.swing.JMenuItem ListadosMenuItem;
    private javax.swing.JMenuItem MaestrosMenuItem;
    private javax.swing.JMenu MenuCompras;
    private javax.swing.JMenu MenuListados;
    private javax.swing.JMenu MenuMaestros;
    private javax.swing.JMenu MenuVentas;
    private javax.swing.JMenuItem VentasMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
